const os = require('node:os')
console.log('Info del sistema operativo:')
console.log('---------------------------')
console.log('Nombre:', os.platform())
console.log('Versión:', os.release())
console.log('Arquitectura:', os.arch())
console.log('CPUs:', os.cpus())
console.log('Memoria Libre:', os.freemem())
console.log('Memoria Total:', os.totalmem())
console.log('Uptime:', os.uptime() / 60 / 60 )